language: node_js

node_js:
  - 8
  - 9
  - 10

before_install:
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
- npm install -g greenkeeper-lockfile@1

before_script:
- greenkeeper-lockfile-update
- npm install

script:
- npm run lint
- npm run test:coverage

after_script: 
- greenkeeper-lockfile-upload
- "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"